### ISSUE TITLE
Using docker-java lib run in container and get nothing from unix socket

### ISSUE THREAD

**Issue by qyvlik** [docker-java/docker-java#1190]
I have a java program which use the docker-java lib, the java program provider the docker-java lib ability pass by websocket. 
If I debug in IDEA, I can get the docker logs. Then I run the java program in docker, and get nothing from unix socket.

docker-compose.yml as follow, and I'm sure the java have the permissions to call the `/var/run/docker.sock`. Any Suggestions?

```
version: '3'

services:
  logs-viewer:
    privileged: true
    image: qyvlik/docker-simple-logs-viewer:latest
    ports:
      - "19102:19102"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./application.yml:/home/www/application.yml:ro
``` 

The qyvlik/docker-simple-logs-viewer:latest source code in here: https://github.com/qyvlik/docker-simple-logs-viewer

docker-java version 

```
        <dependency>
            <groupId>com.github.docker-java</groupId>
            <artifactId>docker-java</artifactId>
            <!-- use latest version https://github.com/docker-java/docker-java/releases -->
            <version>3.1.1</version>
        </dependency>
```
